"""tambah-model

Revision ID: 7662a894f68a
Revises: 79349f547562
Create Date: 2023-10-21 22:15:22.096577

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7662a894f68a'
down_revision = '79349f547562'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jurusan',
    sa.Column('kode_jurusan', sa.Integer(), nullable=False),
    sa.Column('nama_jurusan', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('kode_jurusan'),
    sa.UniqueConstraint('nama_jurusan')
    )
    op.create_table('mahasiswa',
    sa.Column('nim', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=30), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('alamat', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('no_telepon', sa.Integer(), nullable=False),
    sa.Column('jurusan_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['jurusan_id'], ['jurusan.kode_jurusan'], ),
    sa.PrimaryKeyConstraint('nim'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nama'),
    sa.UniqueConstraint('no_telepon'),
    sa.UniqueConstraint('password')
    )
    op.drop_index('nama_prodi', table_name='prodi')
    op.drop_table('prodi')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prodi',
    sa.Column('kode_prodi', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nama_prodi', mysql.VARCHAR(length=30), nullable=False),
    sa.PrimaryKeyConstraint('kode_prodi'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('nama_prodi', 'prodi', ['nama_prodi'], unique=False)
    op.drop_table('mahasiswa')
    op.drop_table('jurusan')
    # ### end Alembic commands ###
