"""db-tugas

Revision ID: 79349f547562
Revises: 
Create Date: 2023-10-20 12:25:16.481080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79349f547562'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prodi',
    sa.Column('kode_prodi', sa.Integer(), nullable=False),
    sa.Column('nama_prodi', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('kode_prodi'),
    sa.UniqueConstraint('nama_prodi')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prodi')
    # ### end Alembic commands ###
