"""ubah-data-anggota

Revision ID: ba6e4b1ba60d
Revises: 5ee5501a9058
Create Date: 2023-10-22 11:28:14.325142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba6e4b1ba60d'
down_revision = '5ee5501a9058'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('keanggotaan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tanggal_masuk', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ukm',
    sa.Column('id_ukm', sa.Integer(), nullable=False),
    sa.Column('nama_ukm', sa.String(length=50), nullable=False),
    sa.Column('deskripsi', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id_ukm'),
    sa.UniqueConstraint('nama_ukm')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ukm')
    op.drop_table('keanggotaan')
    # ### end Alembic commands ###
