"""tanggal-lahir

Revision ID: ca2b397a9120
Revises: 7662a894f68a
Create Date: 2023-10-21 22:28:53.594571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca2b397a9120'
down_revision = '7662a894f68a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mahasiswa', sa.Column('tanggal_lahir', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mahasiswa', 'tanggal_lahir')
    # ### end Alembic commands ###
