"""ubah-data

Revision ID: cea20acd0f51
Revises: de5d9acf1fbd
Create Date: 2023-10-22 12:13:27.034802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cea20acd0f51'
down_revision = 'de5d9acf1fbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('keanggotaan', sa.Column('mahasiswa_id', sa.Integer(), nullable=True))
    op.add_column('keanggotaan', sa.Column('ukm_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'keanggotaan', 'mahasiswa', ['mahasiswa_id'], ['nim'])
    op.create_foreign_key(None, 'keanggotaan', 'ukm', ['ukm_id'], ['id_ukm'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'keanggotaan', type_='foreignkey')
    op.drop_constraint(None, 'keanggotaan', type_='foreignkey')
    op.drop_column('keanggotaan', 'ukm_id')
    op.drop_column('keanggotaan', 'mahasiswa_id')
    # ### end Alembic commands ###
