"""ubah-data

Revision ID: de5d9acf1fbd
Revises: 8b8ab992e52e
Create Date: 2023-10-22 12:10:25.809730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de5d9acf1fbd'
down_revision = '8b8ab992e52e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('keanggotaan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tanggal_masuk', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('keanggotaan')
    # ### end Alembic commands ###
